### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by john-french** [gmit-sweng-20/ca5-bdd-tdd-cycle2-SerjiVutinss#6]
@SerjiVutinss  Your controller tests are very tightly bound to the database in a couple of places, including [e.g. here](https://github.com/gmit-sweng-20/ca5-bdd-tdd-cycle2-SerjiVutinss/blob/198123cade29de38d573d652fac41f07b72107a6/rottenpotatoes/spec/controllers/movies_controller_spec.rb#L127). This works but makes them brittle, and also means they're making real changes to a real database every time they run. Tests at this level should be isolated, that's why mocks/doubles are useful, they help to remove this db dependency.

Please close this issue to acknowledge receipt of feedback.

**Comment by SerjiVutinss** [comment]
Thanks for the feedback @john-french . I had meant to switch these over to mock data alright but ultimately forgot.  I'll be sure to use mock data in the project.
